version: "3.2"
services:
  mysql:
    image: mariadb:latest
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
    build:
      context: "./mysql/"

  vue:
    image: node:current-alpine
    container_name: vue
    working_dir: /home/node/app
    volumes:
      - ./ui:/home/node/app
    environment:
      NODE_ENV: development
    command: "npm run serve"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev.conf.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    container_name: nginx
    depends_on:
      - lumen

  lumen:
    build:
      context: "./php/"
    container_name: lumen
    volumes:
      - ./backend:/app
    depends_on:
      - mysql

volumes:
  data:
